name: Securitydeep Scan

on: [push, workflow_dispatch]

jobs:
  scan_job:
    runs-on: ubuntu-latest
    name: Foss scanner
    steps:
      - name: Run foss Scan
        uses: sdthatte/actions/foss@main
        with:
          threshold: "critical=0 high=5"
